# Generated by Django 4.1.4 on 2022-12-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_at", models.DateTimeField(auto_created=True)),
                ("create_at", models.DateTimeField(auto_created=True)),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=255)),
                ("keywords", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("price", models.FloatField()),
                ("amount", models.IntegerField()),
                ("detail", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Evet"), ("False", "Hayır")], max_length=10
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
        ),
    ]
