# Generated by Django 4.1.4 on 2022-12-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
